# Generated by Django 3.1.6 on 2021-02-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('contact_date', models.DateField(auto_now_add=True)),
                ('contact_time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
