# Generated by Django 3.1.6 on 2021-02-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210220_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contact_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='contact_time',
            field=models.TimeField(blank=True),
        ),
    ]
