# Generated by Django 3.1.6 on 2021-02-20 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210220_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='contact_time',
        ),
    ]
