# Generated by Django 3.1.6 on 2021-02-20 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
