# Generated by Django 3.1.6 on 2021-02-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210220_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
