# Generated by Django 3.1.6 on 2021-02-15 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_contact_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
