# Generated by Django 3.1.6 on 2021-02-15 18:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='timeStamp',
            new_name='contact_time',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
