# Generated by Django 3.1.6 on 2021-02-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210216_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquire',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13)),
                ('content', models.TextField()),
                ('contact_date', models.DateField(auto_now_add=True)),
                ('contact_time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
